version: "3.3"

services:
  server:
    build:
      context: ../
      dockerfile: docker/server/Dockerfile
    ports:
      - 7171:7171
      - 7172:7172
    volumes:
      - ../data:/otbr/data/
    depends_on:
      - mysql
      - login
    links:
      - mysql
    environment:
      - SERVER_DB_HOST=mysql

  mysql:
    build:
      context: ../
      dockerfile: docker/mysql/Dockerfile
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=canary
      - MYSQL_USER=canary
      - MYSQL_PASSWORD=canary
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    ports:
      - 3306:3306

  website-nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./data/web/:/tmp/web/
      - ./:/tmp/otserver/
      - ./data/nginx/:/etc/nginx/conf.d/
    depends_on:
      - mysql
      - website-php
    links:
      - website-php

  website-php:
    restart: unless-stopped
    image: php:7-fpm
    volumes:
      - ./data/web/:/tmp/web/
    depends_on:
      - mysql

  login:
    image: opentibiabr/login-server:latest
    restart: unless-stopped
    ports:
      - 80:8080
    depends_on:
      - mysql
    environment:
      - DB_DATABASE=canary
      - DB_HOSTNAME=mysql
      - DB_PORT=3306
      - DB_PASSWORD=canary
      - DB_USERNAME=canary
      - ENV_LOG_LEVEL=verbose
      - ENV_TYPE=dev
      - LOGIN_PORT=8080
      - SERVER_NAME=Canary
      - SERVER_LOCATION=Bra
      - SERVER_IP=127.0.0.1
      - SERVER_PORT=7172
#      - VOCATIONS -- map your custom vocations here, if needed, comma separated
