version: "3.3"

services:
  server:
    build:
      context: ../
      dockerfile: docker/server/Dockerfile
    restart: always
    ports:
      - 7171:7171
      - 7172:7172
    volumes:
      - ../data:/otbr/data
    depends_on:
      - mysql
      - website
      - login
    links:
      - mysql
    environment:
      - SERVER_DB_HOST=mysql

  mysql:
    build:
      context: ../
      dockerfile: docker/mysql/Dockerfile
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=canary
      - MYSQL_USER=canary
      - MYSQL_PASSWORD=canary
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    ports:
      - 3306:3306

  website:
    image: webdevops/php-nginx:alpine-php7
    restart: unless-stopped
    environment:
      - WEB_DOCUMENT_ROOT=/tmp/web/
      - WEB_DOCUMENT_INDEX=index.php
    ports:
      - 8080:80
    volumes:
      - ./docker/data/web:/tmp/web
      - ./:/tmp/otserver/
    depends_on:
      - mysql

  login-server:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    ports:
      - 80:80
      - 9090:9090
    depends_on:
      - mysql
    environment:
      - LOGIN_HTTP_PORT=80
      - LOGIN_GRPC_PORT=9090
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DBNAME=canary
      - MYSQL_USER=canary
      - MYSQL_PASS=canary
      - SERVER_NAME=Canary
      - SERVER_IP=127.0.0.1
      - SERVER_PORT=7172
      - SERVER_LOCATION=NL
      - RATE_LIMITER_RATE=3000000000000
      - RATE_LIMITER_BURST=53000000000000
