---
name: "PR - Labeler"
on:
  - pull_request_target

jobs:
  triage:
    runs-on: linux
    steps:
      - uses: actions/labeler@main
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
